import { Storage } from '@google-cloud/storage';

export type LogoContentType = 'image/png' | 'image/jpeg' | 'image/webp';

export interface StoredLogo {
  readonly bytes: Buffer;
  readonly contentType: LogoContentType;
}

/** Port for lender-logo objects. Keys are always generated by the API, never by clients. */
export interface LogoStorage {
  put(key: string, logo: StoredLogo): Promise<void>;
  get(key: string): Promise<StoredLogo | null>;
  delete(key: string): Promise<void>;
}

export const maxLogoBytes = 512 * 1024;

const extensions: Record<LogoContentType, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
};

export function logoExtension(contentType: LogoContentType): string {
  return extensions[contentType];
}

/**
 * Identifies an image from its leading bytes. The declared Content-Type must agree,
 * so a script or SVG cannot be stored under an image label.
 */
export function sniffLogo(bytes: Buffer): LogoContentType | null {
  if (
    bytes.length >= 8 &&
    bytes
      .subarray(0, 8)
      .equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))
  )
    return 'image/png';
  if (
    bytes.length >= 3 &&
    bytes[0] === 0xff &&
    bytes[1] === 0xd8 &&
    bytes[2] === 0xff
  )
    return 'image/jpeg';
  if (
    bytes.length >= 12 &&
    bytes.subarray(0, 4).toString('ascii') === 'RIFF' &&
    bytes.subarray(8, 12).toString('ascii') === 'WEBP'
  )
    return 'image/webp';
  return null;
}

/** Private bucket accessed with the Cloud Run service identity (no key files). */
export class GcsLogoStorage implements LogoStorage {
  private readonly bucket;

  constructor(bucketName: string, storage = new Storage()) {
    this.bucket = storage.bucket(bucketName);
  }

  async put(key: string, logo: StoredLogo): Promise<void> {
    await this.bucket.file(key).save(logo.bytes, {
      contentType: logo.contentType,
      resumable: false,
      // Fail rather than overwrite: keys are unique per upload.
      preconditionOpts: { ifGenerationMatch: 0 },
      metadata: { cacheControl: 'private, max-age=300' },
    });
  }

  async get(key: string): Promise<StoredLogo | null> {
    const file = this.bucket.file(key);
    try {
      const [bytes] = await file.download();
      const [metadata] = await file.getMetadata();
      const contentType = sniffLogo(bytes);
      if (!contentType || metadata.contentType !== contentType) return null;
      return { bytes, contentType };
    } catch (error) {
      if (
        typeof error === 'object' &&
        error !== null &&
        'code' in error &&
        error.code === 404
      )
        return null;
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    await this.bucket.file(key).delete({ ignoreNotFound: true });
  }
}

/** Development and test adapter; refused by configuration in production. */
export class MemoryLogoStorage implements LogoStorage {
  private readonly objects = new Map<string, StoredLogo>();

  put(key: string, logo: StoredLogo): Promise<void> {
    this.objects.set(key, {
      bytes: Buffer.from(logo.bytes),
      contentType: logo.contentType,
    });
    return Promise.resolve();
  }

  get(key: string): Promise<StoredLogo | null> {
    return Promise.resolve(this.objects.get(key) ?? null);
  }

  delete(key: string): Promise<void> {
    this.objects.delete(key);
    return Promise.resolve();
  }

  keys(): readonly string[] {
    return [...this.objects.keys()];
  }
}
